[project]
name = "vrfinance-api"
version = "0.1.0"
description = "Backend API for vrfinance"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.118.3",
    "jinja2>=3.1.6",
]
