services:
    db:
        image: postgres:16
        container_name: vrfinance_db
        restart: always
        environment:
            POSTGRES_USER: backend
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: vrfinance
        ports:
            - "5431:5431"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
        build: ./backend
        container_name: vrfinance_backend
        depends_on:
            - db
        environment:
            PGUSER: backend
            PGPASSWORD: secret
            PGDATABASE: vrfinance
            PGHOST: db
            PGPORT: 5432
            PORT: 3000
        ports:
            - "3000:3000"
        command: npm start

    frontend:
        build: ./frontend
        container_name: vrfinance_frontend
        depends_on:
            - backend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certs:/etc/letsencrypt:ro

volumes:
    db_data: {}
